[tool.poetry]
name = "website"
version = "0.1.0"
description = "Dental Dynamix company Django website"
authors = ["Dental Dynamix <support@dentaldynamix.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
asgiref = "3.7.2"
captcha = "0.5.0"
django = "5.0.2"
django-js-asset = "2.2.0"
numpy = "1.26.4"
pillow = "10.2.0"
sqlparse = "0.4.4"
tzdata = "2023.4"
python-decouple = "^3.8"
requests = "^2.32.3"
psycopg2-binary = "^2.9.10"
django-ckeditor-5 = "^0.2.15"
gunicorn = "^21.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
